# Site settings
title: The Rhapsody
email: nelsonkimaiga@aol.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Nelson Kimaiga, a web developer. In the web world, I'm the author of
  The Rhapsody blog. Ideally, I don't design sites, I make them work.
  My expertise and interest lies in front-end technologies, including HTML/5,
  CSS, JavaScript.
  My server side skills revolve around JSP(Java Servlets) and Python.
  I also focus on open source contributing and pro-bono, as they open a world
  of possibilities and rewards for their hard-working developers.
baseurl: "/jekyllRhapsody" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: Nelsonguto
github_username:  nelsonkimaiga

# Build settings
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
